name: Eric J. Alexander
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
exclude: ['README.md','_drafts']
gems:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5

theme: jekyll-theme-modernist